###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun
$windowSwitcher = rofi -show window
$piPrompt = bash -c 'input="$(rofi -dmenu -p "Pedir instrucción a Pi")"; [ -z "$input" ] && exit 0; kitty --class kitty --hold -e distrobox-enter arch -- pi "$input"'
