###################
### AUTOSTART ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
#

exec-once = noctalia-shell
exec-once = nextcloud
exec-once = flatpak run com.discordapp.Discord
exec-once = elephant
#exec-once = flatpak run com.valvesoftware.Steam
#exec-once = xdg-mime default org.kde.dolphin.desktop inode/directory
exec-once = mpvpaper -o "no-audio loop hwdec=auto" '*' ~/Videos/wallpapers/fondo.mp4
