#############################
### ENVIRONMENT VARIABLES ###
#############################

env = NIXOS_OZONE_WL,1
env = MOZ_ENABLE_WAYLAND,1
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_CURRENT_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME_QT6,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = GTK_THEME,catppuccin-macchiato-teal-standard
env = XCURSOR_THEME,Catppuccin-Macchiato-Teal-Cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GDK_BACKEND,wayland,x11
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = TERMINAL,kitty
