package theme

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const GeneratedMarker = "Generated by orgm-hypr theme"

type WallpaperInfo struct {
	Brightness      float64
	BrightnessKnown bool
}

type ResolvedPalette struct {
	Mode    string
	Palette Palette
}

type PlanOptions struct {
	Mode       string
	StateHome  string
	CacheHome  string
	ConfigHome string
	Wallpaper  WallpaperInfo
}

type ApplyPlan struct {
	ThemeID  string
	Mode     string
	Writes   []PlannedWrite
	Reloads  []PlannedReload
	Warnings []string
}

type PlannedWrite struct {
	Target  string
	Path    string
	Content []byte
	Mode    int
}

type PlannedReload struct {
	Target  string
	Command string
}

func ResolvePalette(theme Theme, mode string, wallpaper WallpaperInfo) (ResolvedPalette, string, error) {
	requested := mode
	if requested == "" {
		requested = theme.DefaultMode
	}
	if requested == "auto" {
		if wallpaper.BrightnessKnown {
			if wallpaper.Brightness >= 0.5 {
				requested = "light"
			} else {
				requested = "dark"
			}
		} else {
			requested = theme.DefaultMode
			warning := fmt.Sprintf("auto mode brightness unavailable; using default mode %s", requested)
			resolved, _, err := ResolvePalette(theme, requested, WallpaperInfo{})
			return resolved, warning, err
		}
	}
	if !validMode(requested) || requested == "auto" {
		return ResolvedPalette{}, "", fmt.Errorf("mode must be dark, light, or auto")
	}
	palette, ok := theme.Palettes[requested]
	if !ok {
		return ResolvedPalette{}, "", fmt.Errorf("theme %q missing palette %q", theme.ID, requested)
	}
	return ResolvedPalette{Mode: requested, Palette: palette}, "", nil
}

func BuildApplyPlan(theme Theme, opts PlanOptions) (ApplyPlan, error) {
	resolved, warning, err := ResolvePalette(theme, opts.Mode, opts.Wallpaper)
	if err != nil {
		return ApplyPlan{}, err
	}
	plan := ApplyPlan{ThemeID: theme.ID, Mode: resolved.Mode}
	if warning != "" {
		plan.Warnings = append(plan.Warnings, warning)
	}

	content, err := paletteContent(theme.ID, resolved)
	if err != nil {
		return ApplyPlan{}, err
	}
	plan.Writes = append(plan.Writes, PlannedWrite{
		Target:  "hypr",
		Path:    filepath.Join(opts.StateHome, "orgm-hypr", "theme", "current", "palette.json"),
		Content: content,
		Mode:    0o600,
	})
	plan.Reloads = append(plan.Reloads, PlannedReload{Target: "hypr", Command: "hyprctl reload"})

	targetNames := make([]string, 0, len(theme.Targets))
	for target := range theme.Targets {
		targetNames = append(targetNames, target)
	}
	sort.Strings(targetNames)
	for _, target := range targetNames {
		switch target {
		case "hypr":
			plan.Writes = append(plan.Writes, renderHypr(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "hypr: source generated colors.conf or read palette.json from Hyprland Lua to apply colors")
		case "waybar":
			plan.Writes = append(plan.Writes, renderWaybar(resolved, opts)...)
			plan.Reloads = append(plan.Reloads, PlannedReload{Target: "waybar", Command: "pkill -SIGUSR2 waybar"})
			plan.Warnings = append(plan.Warnings, fmt.Sprintf("waybar: import %s from style.css and reload Waybar", filepath.Join(opts.ConfigHome, "waybar-hypr", "orgm-hypr-theme.css")))
		case "nwg-dock":
			plan.Writes = append(plan.Writes, renderNWGDock(resolved, opts)...)
			plan.Reloads = append(plan.Reloads, PlannedReload{Target: "nwg-dock", Command: "hypr-nwg-dock restart"})
			plan.Warnings = append(plan.Warnings, fmt.Sprintf("nwg-dock: point nwg-dock-hyprland to %s and restart dock", filepath.Join(opts.ConfigHome, "nwg-dock-hyprland", "orgm-hypr-theme.css")))
		case "gtk":
			plan.Writes = append(plan.Writes, renderGTK(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "gtk: generated settings/CSS require GTK apps to restart or import the CSS manually")
		case "qt":
			plan.Writes = append(plan.Writes, renderQt(resolved, opts)...)
			plan.Warnings = append(plan.Warnings, "qt: generated qt5ct/qt6ct files require selecting orgm-hypr config or restarting Qt apps")
		case "chromium", "zen":
			plan.Warnings = append(plan.Warnings, fmt.Sprintf("%s target placeholder: export renderer not implemented in this slice", target))
		default:
			return ApplyPlan{}, fmt.Errorf("invalid target %q", target)
		}
	}
	return plan, nil
}

func renderHypr(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	content := fmt.Sprintf(`# %s
# mode: %s
$background = rgba(%sff)
$surface = rgba(%sff)
$surface_alt = rgba(%sff)
$foreground = rgba(%sff)
$muted = rgba(%sff)
$accent = rgba(%sff)
$accent2 = rgba(%sff)
$border = rgba(%sff)
$urgent = rgba(%sff)
$success = rgba(%sff)
`, GeneratedMarker, resolved.Mode,
		hexNoHash(resolved.Palette.Background), hexNoHash(resolved.Palette.Surface), hexNoHash(resolved.Palette.SurfaceAlt),
		hexNoHash(resolved.Palette.Foreground), hexNoHash(resolved.Palette.Muted), hexNoHash(resolved.Palette.Accent),
		hexNoHash(resolved.Palette.Accent2), hexNoHash(resolved.Palette.Border), hexNoHash(resolved.Palette.Urgent), hexNoHash(resolved.Palette.Success))
	return []PlannedWrite{{Target: "hypr", Path: filepath.Join(opts.StateHome, "orgm-hypr", "theme", "current", "hypr", "colors.conf"), Content: []byte(content), Mode: 0o600}}
}

func renderWaybar(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	content := fmt.Sprintf(`/* %s */
@define-color background %s;
@define-color surface %s;
@define-color surface_alt %s;
@define-color foreground %s;
@define-color muted %s;
@define-color accent %s;
@define-color accent2 %s;
@define-color border %s;
@define-color urgent %s;
@define-color success %s;
`, GeneratedMarker, p.Background, p.Surface, p.SurfaceAlt, p.Foreground, p.Muted, p.Accent, p.Accent2, p.Border, p.Urgent, p.Success)
	return []PlannedWrite{{Target: "waybar", Path: filepath.Join(opts.ConfigHome, "waybar-hypr", "orgm-hypr-theme.css"), Content: []byte(content), Mode: 0o600}}
}

func renderNWGDock(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	r, g, b := rgbValues(p.Background)
	content := fmt.Sprintf(`/* %s */
window {
	background: rgba(%d, %d, %d, 0.88);
	border: 1px solid %s;
	border-radius: 10px;
}

button {
	color: %s;
	background: transparent;
}

button:hover,
button:focus,
button:checked,
button.active {
	background: %s;
	color: %s;
}
`, GeneratedMarker, r, g, b, p.Accent, p.Foreground, p.SurfaceAlt, p.Foreground)
	return []PlannedWrite{{Target: "nwg-dock", Path: filepath.Join(opts.ConfigHome, "nwg-dock-hyprland", "orgm-hypr-theme.css"), Content: []byte(content), Mode: 0o600}}
}

func renderGTK(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	dark := resolved.Mode == "dark"
	preferDark := "false"
	themeName := "Adwaita"
	if dark {
		preferDark = "true"
		themeName = "Adwaita-dark"
	}
	settings := fmt.Sprintf(`# %s
[Settings]
gtk-application-prefer-dark-theme=%s
gtk-theme-name=%s
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=Adwaita
`, GeneratedMarker, preferDark, themeName)
	css := fmt.Sprintf(`/* %s */
@define-color accent_color %s;
@define-color window_bg_color %s;
@define-color window_fg_color %s;
@define-color view_bg_color %s;
@define-color view_fg_color %s;
@define-color headerbar_bg_color %s;
@define-color borders %s;
@define-color error_color %s;
@define-color success_color %s;
`, GeneratedMarker, p.Accent, p.Background, p.Foreground, p.Surface, p.Foreground, p.SurfaceAlt, p.Border, p.Urgent, p.Success)
	writes := []PlannedWrite{}
	for _, version := range []string{"gtk-3.0", "gtk-4.0"} {
		writes = append(writes,
			PlannedWrite{Target: "gtk", Path: filepath.Join(opts.ConfigHome, version, "orgm-hypr-settings.ini"), Content: []byte(settings), Mode: 0o600},
			PlannedWrite{Target: "gtk", Path: filepath.Join(opts.ConfigHome, version, "orgm-hypr-theme.css"), Content: []byte(css), Mode: 0o600},
		)
	}
	return writes
}

func renderQt(resolved ResolvedPalette, opts PlanOptions) []PlannedWrite {
	p := resolved.Palette
	style := "Fusion"
	if resolved.Mode == "dark" {
		style = "Darkly"
	}
	colors := fmt.Sprintf(`# %s
[ColorScheme]
name=orgm-hypr-%s
active_colors=%s, %s, %s, %s, %s, %s, %s
disabled_colors=%s, %s, %s, %s, %s, %s, %s
inactive_colors=%s, %s, %s, %s, %s, %s, %s
`, GeneratedMarker, resolved.Mode,
		p.Foreground, p.Background, p.SurfaceAlt, p.Surface, p.Surface, p.Foreground, p.Accent,
		p.Muted, p.Background, p.SurfaceAlt, p.Surface, p.Surface, p.Muted, p.Border,
		p.Foreground, p.Background, p.SurfaceAlt, p.Surface, p.Surface, p.Foreground, p.Accent)
	writes := []PlannedWrite{}
	for _, version := range []string{"qt5ct", "qt6ct"} {
		colorPath := filepath.Join(opts.ConfigHome, version, "colors", "orgm-hypr.colors")
		conf := fmt.Sprintf(`# %s
[Appearance]
color_scheme_path=%s
custom_palette=true
icon_theme=Adwaita
standard_dialogs=default
style=%s
`, GeneratedMarker, colorPath, style)
		writes = append(writes,
			PlannedWrite{Target: "qt", Path: colorPath, Content: []byte(colors), Mode: 0o600},
			PlannedWrite{Target: "qt", Path: filepath.Join(opts.ConfigHome, version, "orgm-hypr.conf"), Content: []byte(conf), Mode: 0o600},
		)
	}
	return writes
}

func hexNoHash(value string) string {
	return strings.TrimPrefix(value, "#")
}

func rgbValues(value string) (int, int, int) {
	hex := strings.TrimPrefix(value, "#")
	return hexByte(hex[0:2]), hexByte(hex[2:4]), hexByte(hex[4:6])
}

func hexByte(value string) int {
	parsed, _ := strconv.ParseInt(value, 16, 0)
	return int(parsed)
}

func paletteContent(themeID string, resolved ResolvedPalette) ([]byte, error) {
	payload := struct {
		Marker  string  `json:"_comment"`
		ThemeID string  `json:"themeID"`
		Mode    string  `json:"mode"`
		Palette Palette `json:"palette"`
	}{
		Marker:  GeneratedMarker,
		ThemeID: themeID,
		Mode:    resolved.Mode,
		Palette: resolved.Palette,
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}
