package theme

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestBuildApplyPlanRendersCoreDesktopTargets(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"gtk":      {"mode": "generated"},
		"hypr":     {"mode": "generated"},
		"nwg-dock": {"mode": "generated"},
		"qt":       {"mode": "generated"},
		"waybar":   {"mode": "generated"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "dark", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "hypr", filepath.Join("/state", "orgm-hypr", "theme", "current", "hypr", "colors.conf"), []string{
		"# Generated by orgm-hypr theme",
		"$background = rgba(000000ff)",
		"$foreground = rgba(eeeeeeff)",
		"$accent = rgba(7777ffff)",
	})
	assertPlanWriteContains(t, plan, "waybar", filepath.Join("/config", "waybar-hypr", "orgm-hypr-theme.css"), []string{
		"/* Generated by orgm-hypr theme */",
		"@define-color background #000000;",
		"@define-color foreground #eeeeee;",
		"@define-color accent #7777ff;",
	})
	assertPlanWriteContains(t, plan, "nwg-dock", filepath.Join("/config", "nwg-dock-hyprland", "orgm-hypr-theme.css"), []string{
		"window {",
		"background: rgba(0, 0, 0, 0.88);",
		"border: 1px solid #7777ff;",
	})
	assertPlanWriteContains(t, plan, "gtk", filepath.Join("/config", "gtk-3.0", "orgm-hypr-settings.ini"), []string{
		"[Settings]",
		"gtk-application-prefer-dark-theme=true",
		"gtk-theme-name=Adwaita-dark",
	})
	assertPlanWriteContains(t, plan, "gtk", filepath.Join("/config", "gtk-4.0", "orgm-hypr-theme.css"), []string{
		"@define-color accent_color #7777ff;",
		"@define-color window_bg_color #000000;",
	})
	assertPlanWriteContains(t, plan, "qt", filepath.Join("/config", "qt5ct", "colors", "orgm-hypr.colors"), []string{
		"[ColorScheme]",
		"active_colors=#eeeeee, #000000, #353438, #201f23, #201f23, #eeeeee, #7777ff",
	})
	assertPlanWriteContains(t, plan, "qt", filepath.Join("/config", "qt6ct", "orgm-hypr.conf"), []string{
		"[Appearance]",
		"color_scheme_path=/config/qt6ct/colors/orgm-hypr.colors",
		"custom_palette=true",
	})
	assertPlanReload(t, plan, "hypr", "hyprctl reload")
	assertPlanReload(t, plan, "waybar", "pkill -SIGUSR2 waybar")
	assertPlanReload(t, plan, "nwg-dock", "hypr-nwg-dock restart")
}

func TestBuildApplyPlanTriangulatesLightModeAndWarnings(t *testing.T) {
	theme := planTestTheme()
	theme.Targets = map[string]map[string]string{
		"gtk":    {"mode": "generated"},
		"qt":     {"mode": "generated"},
		"waybar": {"mode": "generated"},
	}

	plan, err := BuildApplyPlan(theme, PlanOptions{Mode: "light", StateHome: "/state", CacheHome: "/cache", ConfigHome: "/config"})

	if err != nil {
		t.Fatalf("BuildApplyPlan() error = %v", err)
	}
	assertPlanWriteContains(t, plan, "waybar", filepath.Join("/config", "waybar-hypr", "orgm-hypr-theme.css"), []string{
		"@define-color background #ffffff;",
		"@define-color foreground #111111;",
		"@define-color accent #333388;",
	})
	assertPlanWriteContains(t, plan, "gtk", filepath.Join("/config", "gtk-3.0", "orgm-hypr-settings.ini"), []string{
		"gtk-application-prefer-dark-theme=false",
		"gtk-theme-name=Adwaita",
	})
	assertPlanWriteContains(t, plan, "qt", filepath.Join("/config", "qt5ct", "orgm-hypr.conf"), []string{
		"style=Fusion",
	})
	wantWarnings := []string{
		"waybar: import /config/waybar-hypr/orgm-hypr-theme.css from style.css and reload Waybar",
		"gtk: generated settings/CSS require GTK apps to restart or import the CSS manually",
		"qt: generated qt5ct/qt6ct files require selecting orgm-hypr config or restarting Qt apps",
	}
	for _, want := range wantWarnings {
		if !planHasWarning(plan, want) {
			t.Fatalf("warnings = %#v, want %q", plan.Warnings, want)
		}
	}
}

func assertPlanWriteContains(t *testing.T, plan ApplyPlan, target, path string, snippets []string) {
	t.Helper()
	for _, write := range plan.Writes {
		if write.Target == target && write.Path == path {
			content := string(write.Content)
			for _, snippet := range snippets {
				if !strings.Contains(content, snippet) {
					t.Fatalf("write %s content = %q, want snippet %q", path, content, snippet)
				}
			}
			return
		}
	}
	t.Fatalf("missing write target=%s path=%s in %#v", target, path, plan.Writes)
}

func assertPlanReload(t *testing.T, plan ApplyPlan, target, command string) {
	t.Helper()
	for _, reload := range plan.Reloads {
		if reload.Target == target && reload.Command == command {
			return
		}
	}
	t.Fatalf("missing reload target=%s command=%s in %#v", target, command, plan.Reloads)
}

func planHasWarning(plan ApplyPlan, want string) bool {
	for _, warning := range plan.Warnings {
		if warning == want {
			return true
		}
	}
	return false
}
