###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = walker --dmenu -p "Apps"
$windowSwitcher = /home/osmarg/.config/hypr/scripts/walker-window-switch.sh
$piPrompt = /home/osmarg/.config/hypr/scripts/pi-walker-prompt.sh