# Hyprland config split by bloques.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

source = ~/.config/hypr/00-monitors.conf
source = ~/.config/hypr/10-programs.conf
source = ~/.config/hypr/20-autostart.conf
source = ~/.config/hypr/30-environment.conf
source = ~/.config/hypr/40-permissions.conf
source = ~/.config/hypr/50-look-and-feel.conf
source = ~/.config/hypr/55-layout.conf
source = ~/.config/hypr/60-input.conf
source = ~/.config/hypr/70-keybindings.conf
source = ~/.config/hypr/80-windows-workspaces.conf
source = ~/.config/hypr/90-noctalia-colors.conf
