###################
### AUTOSTART ###
###################

exec-once = orgm-hypr session import-env
exec-once = systemctl --user start graphical-session.target

# Waybar replaces NWG panel.
exec-once = orgm-hypr waybar watch ~/.config/waybar-hypr
exec-once = swaync
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11,ssh
exec-once = hyprpolkitagent
exec-once = orgm-hypr wallpaper restore
exec-once = orgm-hypr wallpaper picker-daemon
exec-once = nextcloud --background
exec-once = orgm-hypr session start-containers arch windows
exec-once = orgm-hypr session start-discord
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
