#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 12
    gaps_out = 12
    border_size = 2
    col.active_border = rgba(8aadf4ee) rgba(f5a97fee) 45deg
    col.inactive_border = rgba(363a4faa)
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 12
    rounding_power = 2
    active_opacity = 0.96
    inactive_opacity = 0.96
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 18
        render_power = 3
        color = rgba(00000070)
    }

    blur {
        enabled = true
        size = 5
        passes = 3
        vibrancy = 0.17
    }
}

layerrule = blur, waybar
layerrule = ignorealpha 0.10, waybar

animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1
    bezier = quick, 0.15, 0, 0.1, 1
    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, almostLinear, popin 87%
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = workspaces, 1, 1.94, almostLinear, fade
}
